// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmlkqbvksxkhpxrtrbpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbGtxYnZrc3hraHB4cnRyYnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MzA2NjIsImV4cCI6MjA3MzMwNjY2Mn0.7YRSjip0p-wOiZMRZ3MG-QEaHg2R3mK4bMPvWQXi54I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});